### ISSUE TITLE
Add base64 checkbox for the Poll trigger

### ISSUE THREAD

**Issue by MykytaDuniashev** [elasticio/sftp-component#128]
# Other Feature Request

## Description

Add a checkbox to the [Poll Files](https://github.com/elasticio/sftp-component#poll-files) trigger which if checked will encode to base64 a file saved to the attachments. This will cover a SQUIZ use case with transferring the image files on our platform.

[Link](https://elasticio.slack.com/archives/C6G1E4WB1/p1707376992480839) to the Slack conversation

**Comment by A3a3e1** [comment]
The checkbox to be added to the actions:
- Download File by name
- Download Files

**Comment by HannaTrotsenko** [comment]
https://github.com/elasticio/sftp-component/releases/tag/1.7.0
