### ISSUE TITLE
Failed to push SFTP component v.1.7.0 refs to Infobip environment

### ISSUE THREAD

**Issue by Glico21** [elasticio/sftp-component#132]
# Internal Issue/Enhancement

## Description

Failed to push SFTP component v.1.7.0 refs to Infobip environment. Error description below.
[SFTP_1.7.0_Infobip_pushing_error_log.txt](https://github.com/user-attachments/files/16067002/SFTP_1.7.0_Infobip_pushing_error_log.txt)

We need to release a fix and successfully re-push the SFTP component on Infobip.

## Definition of Done

- [ ] Release a fix
- [ ] Push it to Infobip repo

**Comment by HannaTrotsenko** [comment]
https://github.com/elasticio/sftp-component/releases/tag/1.7.1
