### ISSUE TITLE
Using the private key for authentication does not function properly

### ISSUE THREAD

**Issue by MykytaDuniashev** [elasticio/sftp-component#133]
# Component Bug Report

## Description

SFTP component fails to work with the private key authentication. The client generates a key pair - public and private keys. The private key should be put into the respective field in the SFTP component [credentials](https://github.com/elasticio/sftp-component#credentials). If everything is correct it should verify the credentials and establish a connection. However, the credentials can't be verified and hence, work properly.

[Link](https://elasticio.slack.com/archives/C6G1E4WB1/p1720598987198499) to a Slack conversation.

[Link](https://app.intercom.com/a/inbox/qgp8r7fl/inbox/shared/all/conversation/10951100103162?view=List) to a conversation with **ABMcloud** that reported the issue

## Component Version

1.7.0

## Actual Result

During the verification process:
```
Warning
We were not able to verify your credential. Please try again or contact the admins of the service you are providing a credential for.
The reasons for that might be an invalid credential data (e.g. expired API key) or a temporal issue with the target service.
```

During the flow execution: 
```
Error: connect: getConnection: All configured authentication methods failed
    at SftpClient.fmtError (/home/node/node_modules/ssh2-sftp-client/src/index.js:111:22)
    at SftpClient.connect (/home/node/node_modules/ssh2-sftp-client/src/index.js:249:37)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Sftp.connect (/home/node/lib/Sftp.js:56:5)
    at async TaskExec.processAction (/home/node/lib/actions/upload.js:17:3)
```

## Expected Result

Credentials are verified and the component connects to a client server.

**Comment by A3a3e1** [comment]
@MykytaDuniashev Please do ask the client - are they trying to use an RSA key? Or anything else, e.g. a ed25519 key?

**Comment by A3a3e1** [comment]
I managed to connect via a Private key only auth method on our Hetzner server from the component

**Comment by A3a3e1** [comment]
Updated the ssh2-sftp-client to 10.0.3 and tested with several different keys:
- RSA, Key length 1024 bits - :x:
- RSA, Key length 4096 bits - :white_check_mark:
- RSA-SHA2-256 - :white_check_mark:
- RSA-SHA2-512 - :white_check_mark:
- ED25519 - :white_check_mark:
- ECDSA - :white_check_mark:

Added it to the Readme of the component

**Comment by MarianaZaloha** [comment]
https://github.com/elasticio/sftp-component/releases/tag/1.7.2
