### ISSUE TITLE
Download Files action doesn't work with the real-time flows

### ISSUE THREAD

**Issue by MykytaDuniashev** [elasticio/sftp-component#135]
# Component Bug Report

## Description

The issue is that the action assumes that the SFTP connection is still alive and does not recreate it. In ordinary flows, it is not a problem, because the connection is established every execution. But in RT flows the client is created and the connection is established only once. And once it drops in a few minutes, the code does not recreate it.

https://github.com/elasticio/sftp-component/blob/ac79d9ffa197feb2499060a9a639e17b977b9d17/lib/actions/lookupObjects.js#L201

[Link](https://elasticio.slack.com/archives/C6G1E4WB1/p1722929814219919) to the Slack conversation

[Link](https://support.elastic.io/a/tickets/9059) to the Techego ticket

## Component Version

1.7.1

## Steps to Reproduce

1. Use SFTP [Download Files](https://github.com/elasticio/sftp-component?tab=readme-ov-file#download-files) action
2. Enable real-time mode in the flow
3. Start the flow (the first executions will succeed and all the further will fail with errors)

## Actual Result

Error: `exists: exists: No SFTP connection available`

## Expected Result

Action should recreate a connection in an RT flow

**Comment by HannaTrotsenko** [comment]
https://github.com/elasticio/sftp-component/releases/tag/1.7.3
