### ISSUE TITLE
Support for custom ports

### ISSUE THREAD

**Issue by benburch** [elasticio/sftp-component#14]
Component is currently hard coded to port 22, request to add in port as a config value so that custom ports can be supported. (Still SFTP, but just on a custom port)

**DoD**

**Component development prerequisites:**

- [x] Development team has all needed requirements
- [x] Access to the needed service with all needed permissions is granted
- [x] No open tasks that could block Component development process
- [x] The E.io’s GitHub repository must be checked if there is another implementation of the component under development. If it exists, new repository should not be created
- [x] Component architecture should be discussed and approved before start coding
- [x] New component GIT repo preconditions:
  - repo type (private/public)
  - license type
- [x] Component deployment preconditions:
  - Where to deploy (app.elastic.io etc..)
  - Component's access level on each installation that component must be deployed on\

**Development:**

- [x] Code is written and formatted in accordance with the Styling guide
- [x] Code (incl. configs, test samples, environment variables etc.) MUST NOT contain any sensitive data like passwords, tokens, API keys etc.
- [x] Component logs does not contain any sensitive data (credentials, input/output requests, Environment variables)
- [x] Code is covered with unit tests
- [x] Component code is covered with integration tests (optional)
- [x] Triggers/actions comply with OIH patterns
- [x] Documentation (README.md file in the Github) is 100% ready
- [x] Changelogs (CHANGELOG.md) are created/updated
- [x] Component's version is updated in package.json according to Semantic Versioning 2.0.0
- [x] CI is set up
- [x] All development branches are reviewed

**After QA:**

- [x] All development branches are merged into master branch
- [x] Sprint review preparation is finished (demo flow is built)

**QA:**

- [x] Test cases for the component are ready at the TestRail
- [x] Functional testing is finished
- [x] Regression testing is finished (optional)
- [x] Component is deployed to the production stage (app.elastic.io) and/or other required stage
  - Component has a proper access level
  - Required Environment Variables are set
  - Smoke test is finished
- [ ] Release notes is done
- [ ] Component Roadmap is updated
- [ ] Component spreadsheet is updated

**Comment by drobiazko** [comment]
@benburch why assigned to me?

**Comment by benburch** [comment]
@drobiazko just thought you were last commit, can put to PS?

**Comment by drobiazko** [comment]
I think so

**Comment by zubairov** [comment]
@A3a3e1 could you please estimate this change so we could potentially plan this for next sprint?

**Comment by A3a3e1** [comment]
@zubairov Code changes require 30 min maximum. But we need to test it. 
So we need a test sftp instance working on a custom port. Not sure about the estimation of this part. Say, roughly it is 8 to 13sp.
@benburch don't you have such a test instance?

**Comment by benburch** [comment]
@A3a3e1 yes, have test instance.. can share details separately.

**Comment by A3a3e1** [comment]
@benburch 👍 
@zubairov Then we need **5sp**.

**Comment by jhorbulyk** [comment]
@benburch This works as a work around
![screenshot from 2018-11-16 18-02-42](https://user-images.githubusercontent.com/5710732/48635964-e2f1dd00-e9c9-11e8-9a2c-9bdae5e698a1.png)
@A3a3e1 Also we have such a system in BitWarden (*A2 Hosting SFTP Credentials*).

Both ideas are things to add to Joerg's internal knowledge base when he gets around to creating it.

**Comment by benburch** [comment]
@jhorbulyk tried that earlier, but appeared to fail still? Perhaps was SSH/SFTP incompatibility instead?

**Comment by A3a3e1** [comment]
Estimation was done with the following assumptions:
- The requested feature is easy to implement (estimation: *5sp*), but:
- The component is outdated.
- The component should conform Definition of Done (DOD), incl. code styling, tests, documentation, CI tools, etc.

**Comment by A3a3e1** [comment]
@ZainNoor99 @shanthoshp please refer this doc for what should be done in the component so that it complies with DOD
https://github.com/elasticio/professional-services-best-practices/blob/master/professional-services-development-guide.md#component-development-definition-of-done-cd-dod-template
