### ISSUE TITLE
Renaming of Attachments

### ISSUE THREAD

**Issue by benburch** [elasticio/sftp-component#15]
When files are written to the SFTP destination the filename is a GUID that was generated by the platform. Can we add support for custom file naming, the filename can be set by the user in the mapping expression?

**Comment by zubairov** [comment]
What if a message contains multiple attachments? How mapping would work in this case?

**Comment by zubairov** [comment]
We can let a user to  provide a pattern  (as field not in metadata) that will be used for to generate a name for a file when storing it

**Comment by jhorbulyk** [comment]
Possible solution provided in https://github.com/elasticio/sftp-component/issues/28
