### ISSUE TITLE
No error message on UI in case of verification of invalid credentials

### ISSUE THREAD

**Issue by stas-fomenko** [elasticio/sftp-component#27]
**Description:** No error message on UI in case of verification of invalid credentials, however in logs user may see that verification has been failed:

**STR:**
1. Start creating new creds for the component via Credentials section *OR* via flow
2. Input invalid creds, for example:
![image](https://user-images.githubusercontent.com/36419533/67200912-b3cfc100-f40d-11e9-8025-9f9cdeaa3369.png)
3. Click on `Verify` button.

**AR:**  
1. No error message on UI regarding creds verification error.
2. An error message is in logs.
3. Message about successfully verified creds:
![image](https://user-images.githubusercontent.com/36419533/67201159-51c38b80-f40e-11e9-89c5-a938dde6c2df.png)
4. `Verify` button became `Verified`:
![image](https://user-images.githubusercontent.com/36419533/67201256-93eccd00-f40e-11e9-9613-9cca8aeab298.png)

**Comment by stas-fomenko** [comment]
In conversation with @dvd-z got information that this may be related to another issue: https://github.com/elasticio/sailor-nodejs/issues/68

![image](https://user-images.githubusercontent.com/36419533/67201463-08c00700-f40f-11e9-8d5a-c5b558156d4c.png)

**Comment by ShkarupaNick** [comment]
we can migrate it to callback style. without changes in the sailor

**Comment by stas-fomenko** [comment]
bug has been fixed in this commit: `1cac6e41e8ac49ebc3dc3cb2c6f7a846871a18b7`
