### ISSUE TITLE
Increase max-payload size to 100MB

### ISSUE THREAD

**Issue by zubairov** [elasticio/sftp-component#6]
Changes required here:

https://github.com/elasticio/sftp-component/blob/master/lib/triggers/read.js#L8

we could consider to make it parameterizable via env-var, but please be carefull as env-vars are ``string``s

**Comment by jhorbulyk** [comment]
Doesn't the code linked already show that the max payload size is 100 MB?

**Comment by zubairov** [comment]
right.

**Comment by jhorbulyk** [comment]
I spent some time testing this and I was able to confirm it worked.  I also opened [this PR](https://github.com/elasticio/sftp-component/pull/7) to update the documentation.
