### ISSUE TITLE
migrate attachment creation process to v2

### ISSUE THREAD

**Issue by khanzadyan** [elasticio/sftp-component#9]
During the creation of signed URL the component is still using the methods in`v1` since it is referencing the `elasticio-rest-node` where the `v1` is used: 
https://github.com/elasticio/elasticio-rest-node/blob/master/lib/client.js

The sftp attachment creation routines are here:
https://github.com/elasticio/sftp-component/blob/master/lib/attachments.js

**Comment by khanzadyan** [comment]
@drobiazko and @zubairov not sure if this is component team job or something which should go into the platform development efforts.

**Comment by ShkarupaNick** [comment]
@zubairov  
in **_API v1_** "**Create a signed url**" operation use endpoint 
https://api.elastic.io/v1/resources/s3/signed-url
while **_API v2_** use endpoint 
https://api.elastic.io/v2/resources/storage/signed-url

What action I should to do?
fix code in **elasticio-rest-node** (change logic of **createSignedUrl()** function to call v2 api)
or make some new function in **sftp-component** which will work with v2 API??

any other idea?

**Comment by zubairov** [comment]
@khanzadyan thoughts? ⬆️

**Comment by zubairov** [comment]
@ShkarupaNick IMO we need to preserve current functionality as is but migrate the code to use v2 instead of v1

**Comment by khanzadyan** [comment]
@zubairov IMHO the client should not know about the used version of API. When they use the attachment in SFTP they are not particularly calling any resource on their own, our component does.

So what is the point of using the soon to be deprecated resource?
